---
title: "8_Conditions"
output: pdf_document
date: "2022-11-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 8. Conditions
## 8.1 Introduction
### 8.1.1 Prerequisites

```{r}
library(rlang)
```

## 8.2 Signalling conditions

```{r, error = T}
stop("This is what an error looks like")

warning("This is what a warning looks like")

message("This is what a message looks like")
```

### 8.2.1 Errors

```{r, error = T}
f <- function() g()
g <- function() h()
h <- function() stop("This is an error!")

f()
```

```{r, error = T}
h <- function() stop("This is an error!", call. = FALSE)
f()
```

```{r, error = T}
h <- function() abort("This is an error!")
f()
```

### 8.2.2 Warnings

```{r}
fw <- function() {
  cat("1\n")
  warning("W1")
  cat("2\n")
  warning("W2")
  cat("3\n")
  warning("W3")
}
```

```{r}
fw()
```


```{r}
options(warn = 0)
# Setting warn to 0 still doesn't fix immediate printing
fw()
```

```{r}
formals(1)

file.remove("this-file-doesn't-exist")

lag(1:3, k = 1.5)

as.numeric(c("18", "30", "50+", "345,678"))
```

### 8.2.3 Messages

```{r}
fm <- function() {
  cat("1\n")
  message("M1")
  cat("2\n")
  message("M2")
  cat("3\n")
  message("M3")
}

fm()
```

```{r}
cat("Hi!\n")

message("Hi!")
```

#### 8.2.4 Exercises

1. Write a wrapper around file.remove() that throws an error if the file to be deleted does not exist.

```{r, error = T}
better.file.remove <- function(file){
  if(file.exists(file)){
    file.remove(file)
  } else{
    stop("File does not exist")
  }
}

better.file.remove("test.txt")
file.create("test.txt")
better.file.remove("test.txt")

```

2. What does the appendLF argument to message() do? How is it related to cat()?

```{r}
message("No Breaks for me", appendLF = F)
message("Now a break", appendLF = T)
message("Woo", appendLF = T)

cat("Hi")
cat("Hello")
```

Basically you can decide to extend the message you already have by setting appendLF to False. `cat()` by default is similar to `message(appendLF = F)`

## 8.3 Ignoring conditions

```{r, error = T}
f1 <- function(x) {
  log(x)
  10
}
f1("x")
```

```{r}
f2 <- function(x) {
  try(log(x))
  10
}
f2("a")
```

```{r}
default <- NULL
try(default <- read.csv("possibly-bad-input.csv"), silent = TRUE)
default
```

```{r}
suppressWarnings({
  warning("Uhoh!")
  warning("Another warning")
  1
})
```

```{r}
suppressMessages({
  message("Hello there")
  2
})
```

```{r}
suppressWarnings({
  message("You can still see me")
  3
})
```

## 8.4 Handling conditions

```{r, error=T}
tryCatch(
  error = function(cnd) {
    # code to run when error is thrown
  },
   code_to_run_while_handlers_are_active
)

withCallingHandlers(
  warning = function(cnd) {
    # code to run when warning is signaled
  },
  message = function(cnd) {
    # code to run when message is signaled
  },
    code_to_run_while_handlers_are_active
)
```

### 8.4.1 Condition objects

```{r}
cnd <- catch_cnd(stop("An error"))
str(cnd)
conditionMessage(cnd)
conditionCall(cnd)
```

### 8.4.2 Exiting handlers

```{r}
f3 <- function(x) {
  tryCatch(
    error = function(cnd) NA,
    log(x)
  )
}

f3("x")
f3(10)
```

```{r}
tryCatch(
  error = function(cnd) 10,
  1 + 1
)

tryCatch(
  error = function(cnd) 10,
  {
    message("Hi!")
    1 + 1
  }
)
```

```{r}
tryCatch(
  message = function(cnd) "There",
  {
    message("Here")
    stop("This code is never run!")
  }
)
```

```{r}
tryCatch(
  error = function(cnd) {
    paste0("--", conditionMessage(cnd), "--")
  },
  stop("This is an error")
)
```

```{r}
path <- tempfile()
tryCatch(
  {
    writeLines("Hi!", path)
    # ...
  },
  finally = {
    # always run
    unlink(path)
  }
)
```

### 8.4.3 Calling handlers

```{r}
tryCatch(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)

withCallingHandlers(
  message = function(cnd) cat("Caught a message!\n"), 
  {
    message("Someone there?")
    message("Why, yes!")
  }
)
```

```{r}
withCallingHandlers(
  message = function(cnd) message("Second message"),
  message("First message")
)
```

```{r}
# Bubbles all the way up to default handler which generates the message
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
# Muffles the default handler which prints the messages
withCallingHandlers(
  message = function(cnd) {
    cat("Level 2\n")
    cnd_muffle(cnd)
  },
  withCallingHandlers(
    message = function(cnd) cat("Level 1\n"),
    message("Hello")
  )
)
```

```{r}
# Muffles level 2 handler and the default handler
withCallingHandlers(
  message = function(cnd) cat("Level 2\n"),
  withCallingHandlers(
    message = function(cnd) {
      cat("Level 1\n")
      cnd_muffle(cnd)
    },
    message("Hello")
  )
)
```

cnd doesn't pass to tlevel 2 and is muffled by level 1

### 8.4.4 Call stacks

```{r}
f <- function() g()
g <- function() h()
h <- function() message("!")
```

```{r}
withCallingHandlers(f(), message = function(cnd) {
  lobstr::cst()
  cnd_muffle(cnd)
})
```

```{r}
tryCatch(f(), message = function(cnd) lobstr::cst())
```

#### 8.4.5 Exercises

1. What extra information does the condition generated by `abort()` contain compared to the condition generated by `stop()` i.e. what’s the difference between these two objects? Read the help for `?abort` to learn more.

```{r, error = T}
catch_cnd(stop("An error"))
catch_cnd(abort("An error"))
```

abort shows you the backtrace of what triggered the error

2. Predict the results of evaluating the following code

```{r}
show_condition <- function(code) {
  tryCatch(
    error = function(cnd) "error",
    warning = function(cnd) "warning",
    message = function(cnd) "message",
    {
      code
      NULL
    }
  )
}

show_condition(stop("!"))
show_condition(10)
show_condition(warning("?!"))
show_condition({
  10
  message("?")
  warning("?!")
})
```

"error", "NULL", "warning", "message"

3. Explain the results of running this code:

```{r}
withCallingHandlers(
  message = function(cnd) message("b"),
  withCallingHandlers(
    message = function(cnd) message("a"),
    message("c")
  )
)
```

`message("c")` triggers the first handler which calls `message(a)` which triggers the second handler. The second handler then messages "b", then the message from the first handler comes through with "a" which retriggers the second handler which sends "b" again. Finally the originally message of "c" is printed

4. Read the source code for `catch_cnd()` and explain how it works.

```{r}
catch_cnd
```

First checks to see if classes is provided as a character object. Creates a list object called handlers which holds the different types of conditions to be caught. Then evaluates the expression using `tryCatch`

5. How could you rewrite `show_condition()` to use a single handler?

```{r}
show_condition
```

```{r}
show_condition2 <- function(code) {
  tryCatch(
    condition = function(cnd) {
      if(is_error(cnd))   return("error")
      if(is_warning(cnd)) return("warning")
      if(is_message(cnd)) return("message")
    },
    {
      code
      NULL
    }
  )
}

show_condition2(stop("!"))
show_condition2(10)
show_condition2(warning("?!"))
show_condition2({
  10
  message("?")
  warning("?!")
})
```

## 8.5 Custom conditions

```{r, error = T}
abort(
  "error_not_found",
  message = "Path `blah.csv` not found", 
  path = "blah.csv"
)
```

### 8.5.1 Motivation

```{r, error = T}
log(letters)
```

```{r, error = T}
log(1:10, base = letters)
```

```{r}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort(paste0(
      "`x` must be a numeric vector; not ", typeof(x), "."
    ))
  }
  if (!is.numeric(base)) {
    abort(paste0(
      "`base` must be a numeric vector; not ", typeof(base), "."
    ))
  }

  base::log(x, base = base)
}
```

```{r, error = T}
my_log(letters)
```

```{r, error = T}
my_log(1:10, base = letters)
```

### 8.5.2 Signalling

```{r}
abort_bad_argument <- function(arg, must, not = NULL) {
  msg <- glue::glue("`{arg}` must {must}")
  if (!is.null(not)) {
    not <- typeof(not)
    msg <- glue::glue("{msg}; not {not}.")
  }
  
  abort("error_bad_argument", 
    message = msg, 
    arg = arg, 
    must = must, 
    not = not
  )
}
```

```{r}
stop_custom <- function(.subclass, message, call = NULL, ...) {
  err <- structure(
    list(
      message = message,
      call = call,
      ...
    ),
    class = c(.subclass, "error", "condition")
  )
  stop(err)
}

err <- catch_cnd(
  stop_custom("error_new", "This is a custom error", x = 10)
)
class(err)
err$x
```

```{r}
my_log <- function(x, base = exp(1)) {
  if (!is.numeric(x)) {
    abort_bad_argument("x", must = "be numeric", not = x)
  }
  if (!is.numeric(base)) {
    abort_bad_argument("base", must = "be numeric", not = base)
  }

  base::log(x, base = base)
}
```

```{r, error = T}
my_log(letters)
```

```{r, error = T}
my_log(1:10, base = letters)
```

### 8.5.3 Handling

```{r}
library(testthat)
```

```{r}
err <- catch_cnd(my_log("a"))
expect_s3_class(err, "error_bad_argument")
expect_equal(err$arg, "x")
expect_equal(err$not, "character")
```

```{r}
tryCatch(
  error_bad_argument = function(cnd) "bad_argument",
  error = function(cnd) "other error",
  my_log("a")
)
```

```{r}
tryCatch(
  error = function(cnd) "other error",
  error_bad_argument = function(cnd) "bad_argument",
  my_log("a")
)
```

#### 8.5.4 Exercises

1. Inside a package, it’s occasionally useful to check that a package is installed before using it. Write a function that checks if a package is installed `(with requireNamespace("pkg", quietly = FALSE))` and if not, throws a custom condition that includes the package name in the metadata.

```{r, error = T}
abort_not_installed <- function(pkg, must){
  msg <- glue::glue("`{pkg}` must {must}")
  
  abort(
    "error_not_installed",
    message = msg,
    pkg = pkg,
    must = must
    )
}

got_it <- function(pkg) {
  if (!requireNamespace(pkg, quietly = FALSE)) {
    abort_not_installed(pkg = pkg, must = "be previously installed to use")
  }
  TRUE
}

got_it("ggplot2")

got_it("ggplot3")
```

2. Inside a package you often need to stop with an error when something is not right. Other packages that depend on your package might be tempted to check these errors in their unit tests. How could you help these packages to avoid relying on the error message which is part of the user interface rather than the API and might change without notice?

Make some custom metadata in a custom condition which the other packages can check for. Make an error class which is unique to your package/error

## 8.6 Applications

### 8.6.1 Failure value

```{r}
fail_with <- function(expr, value = NULL) {
  tryCatch(
    error = function(cnd) value,
    expr
  )
}

fail_with(log(10), NA_real_)
fail_with(log("x"), NA_real_)
```

```{r}
try2 <- function(expr, silent = FALSE) {
  tryCatch(
    error = function(cnd) {
      msg <- conditionMessage(cnd)
      if (!silent) {
        message("Error: ", msg)
      }
      structure(msg, class = "try-error")
    },
    expr
  )
}

try2(1)

try2(stop("Hi"))

try2(stop("Hi"), silent = TRUE)

```

### 8.6.2 Success and failure values

```{r}
foo <- function(expr) {
  tryCatch(
    error = function(cnd) error_val,
    {
      expr
      success_val
    }
  )
}
```

```{r}
does_error <- function(expr) {
  tryCatch(
    error = function(cnd) TRUE,
    {
      expr
      FALSE
    }
  )
}
```

```{r}
catch_cnd <- function(expr) {
  tryCatch(
    condition = function(cnd) cnd, 
    {
      expr
      NULL
    }
  )
}
```

```{r}
safety <- function(expr) {
  tryCatch(
    error = function(cnd) {
      list(result = NULL, error = cnd)
    },
    list(result = expr, error = NULL)
  )
}

str(safety(1 + 10))

str(safety(stop("Error!")))
```

### 8.6.3 Resignal

```{r}
warning2error <- function(expr) {
  withCallingHandlers(
    warning = function(cnd) abort(conditionMessage(cnd)),
    expr
  )
}
```

```{r, error = T}
warning2error({
  x <- 2 ^ 4
  warn("Hello")
})
```

### 8.6.4 Record

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }
  
  withCallingHandlers(
    message = add_cond,
    warning = add_cond,
    expr
  )
  
  conds
}

catch_cnds({
  inform("a")
  warn("b")
  inform("c")
})
```

```{r}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }
  
  tryCatch(
    error = function(cnd) {
      conds <<- append(conds, list(cnd))
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )
  
  conds
}

catch_cnds({
  inform("a")
  warn("b")
  abort("C")
})
```

### 8.6.5 No default behaviour

```{r}
log <- function(message, level = c("info", "error", "fatal")) {
  level <- match.arg(level)
  signal(message, "log", level = level)
}
```

```{r}
log("This code was run")
```

```{r}
record_log <- function(expr, path = stdout()) {
  withCallingHandlers(
    log = function(cnd) {
      cat(
        "[", cnd$level, "] ", cnd$message, "\n", sep = "",
        file = path, append = TRUE
      )
    },
    expr
  )
}

record_log(log("Hello"))
```

```{r}
ignore_log_levels <- function(expr, levels) {
  withCallingHandlers(
    log = function(cnd) {
      if (cnd$level %in% levels) {
        cnd_muffle(cnd)
      }
    },
    expr
  )
}

record_log(ignore_log_levels(log("Hello"), "info"))
```

#### If you create a condition object by hand, and signal it with signalCondition(), cnd_muffle() will not work. Instead you need to call it with a muffle restart defined, like this:

```{r, error = T}
withRestarts(signalCondition(cond), muffle = function() NULL)
```

#### 8.6.6 Exercises

1. Create `suppressConditions()` that works like `suppressMessages()` and `suppressWarnings()` but suppresses everything. Think carefully about how you should handle errors.

```{r, error = T}
suppressConditions <- function(expr){
  tryCatch(
    error = function(cnd) invisible(cnd),
    interrupt = function(cnd) invisible(cnd),
    warning = function(cnd) invisible(cnd),
    message = function(cnd) invisible(cnd),
    expr
  )
}

error_obj <- suppressConditions({
  message("message")
  warning("warning")
  abort("error")
})

error_obj

error_obj2 <- suppressConditions({log10("a")})
error_obj2

error_obj3 <- suppressConditions({log10(10)})
error_obj3
```

2. Compare the following two implementations of `message2error()`. What is the main advantage of `withCallingHandlers()` in this scenario? (Hint: look carefully at the traceback.)

```{r, error = T}
message2error <- function(code) {
  withCallingHandlers(code, message = function(e) stop(e))
}
message2error(message("aaa"))
```

```{r, error = T}
message2error <- function(code) {
  tryCatch(code, message = function(e) stop(e))
}
message2error(message("aaa"))
```

It doesn't throw an error and prints the message in the first one. Easier to work with the first than the second.

3. How would you modify the `catch_cnds()` definition if you wanted to recreate the original intermingling of warnings and messages?

```{r, error = T}
catch_cnds <- function(expr) {
  conds <- list()
  add_cond <- function(cnd) {
    conds <<- append(conds, list(cnd))
    cnd_muffle(cnd)
  }
  
  tryCatch(
    error = function(cnd) {
      conds <<- append(conds, list(cnd))
    },
    withCallingHandlers(
      message = add_cond,
      warning = add_cond,
      expr
    )
  )
  
  conds
}
```

4. Why is catching interrupts dangerous? Run this code to find out.

```{r, error = T}
bottles_of_beer <- function(i = 99) {
  message(
    "There are ", i, " bottles of beer on the wall, ", 
    i, " bottles of beer."
  )
  while(i > 0) {
    tryCatch(
      Sys.sleep(1),
      interrupt = function(err) {
        i <<- i - 1
        if (i > 0) {
          message(
            "Take one down, pass it around, ", i, 
            " bottle", if (i > 1) "s", " of beer on the wall."
          )
        }
      }
    )
  }
  message(
    "No more bottles of beer on the wall, ", 
    "no more bottles of beer."
  )
}
```

Death loops where you can't exit until i is equal to 0